### ISSUE TITLE
SolvedTicket#001

### ISSUE THREAD

**Issue by OrphanClark** [thekingofspace/MekanismBridge#1]
I used the following
Alchemistry
AlchemyLib
ChemLib
Mekanism
Mekanism: Generators
Mekanism: Tools
Mekanism: Additions
Mekanism: Abriged

Using without your mod works fine, but with it, the launcher results in:
![image](https://github.com/thekingofspace/MekanismBridge/assets/134181041/5cfb8a9c-6b28-4178-9f05-dc2a4d1ac755)

Forge, Version 43.2.21

Your idea is a lovely one, a mod to properly fuse Alchemistry and Mekanism.
Don't let an issue discourage you, I'm sure you'll do fine in the future.👍

Also, as a request in future updates, after you've fixed whatever bout has occurred, could you add a way to make polonium and plutonium pellets with Alchemistry?

**Comment by thekingofspace** [comment]
Will look into this issues, however today I did post a update that might fix your issues

and the polonium idea I will look into

**Comment by thekingofspace** [comment]
Issues has been resolved will be pushing update out soon!
