### ISSUE TITLE
SolvedTicket#002

### ISSUE THREAD

**Issue by OrphanClark** [thekingofspace/MekanismBridge#2]
https://github.com/thekingofspace/MekanismBridge/assets/134181041/350db595-e7cf-4079-b93e-7d5e17570e53

Play with sound, much better.

I used the following
Alchemistry
AlchemyLib
ChemLib
Immersive Engineering
Mekanism
Mekanism: Generators
Mekanism: Tools
Mekanism: Additions
Mekanism: Abriged

Despite having Immersive Engineering at the required update, it registers as "not installed".

Using without your mod works fine, but with it, Minecraft results in:
![image](https://github.com/thekingofspace/MekanismBridge/assets/134181041/2b7e606c-db08-4b92-85e6-bfb52ea340d9)

Forge, Version 43.2.21
Mod, Version MekanismBridge1.19.2-2.1.jar (Latest)

Your so close to a functional mod, it's right in front of you!
I have faith in your abilities!

**Comment by thekingofspace** [comment]
Oh crap uhm ok I will fix that sorry about that!

**Comment by thekingofspace** [comment]
Issue has been resolved with in the current version. update will be pushed later!
